task:
  dataset_type: celebs_sketch_to_face
  encoder_type: GradualStyleEncoder
  start_from_latent_avg: True
  label_nc: 1
  input_nc: 1
loss:
  lpips_lambda: 0.8
  l2_lambda: 1
  id_lambda: 0
  w_norm_lambda: 0.00
compute:
  workers: 8
  test_workers: 8
  batch_size: 8
  test_batch_size: 8
log:
  val_interval: 2500
  save_interval: 5000
